Anyx\LoginGateBundle\Document\FailureLoginAttempt:
    type: document
    repositoryClass: Anyx\LoginGateBundle\Document\FailureLoginAttemptRepository
    fields:
        id:
            type: id
            id: true
        ip:
            type: string
            index: true
        createdAt:
            type: date
        data:
            type: hash
